updated template and action

diff --git a/.github/workflows/combined_format_lint_test_mypy.yml b/.github/workflows/combined_format_lint_test_mypy.yml
--- a/.github/workflows/combined_format_lint_test_mypy.yml
+++ b/.github/workflows/combined_format_lint_test_mypy.yml
@@ -96,7 +96,15 @@ jobs:
         run: |
           COMMIT_HASH=$(git rev-parse HEAD)
           echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
-  
+
+      - name: Check if changelog has been updated
+        run: |
+          if echo "${ALL_CHANGED_FILES}" | grep -q "changelog.md"; then
+            echo "changelog.md has been updated."
+          else
+            echo "Error: changelog.md must be updated for this PR."
+            exit 1
+          fi
 
   lint_test_type_check:
     name: Lint, Test, Coverage, and Type Checking
