creating dummy dev branch

diff --git a/.github/workflows/combined_format_lint_test_mypy.yml b/.github/workflows/combined_format_lint_test_mypy.yml
--- a/.github/workflows/combined_format_lint_test_mypy.yml
+++ b/.github/workflows/combined_format_lint_test_mypy.yml
@@ -2,9 +2,9 @@ name: Format, Lint, Test, Coverage, and Type Checking
 
 on:
   push:
-    branches: [ dev ]
+    branches: [ dummy-dev ]
   pull_request:
-    branches: [ dev ]
+    branches: [ dummy-dev ]
   workflow_dispatch:
 
 env:
@@ -35,11 +35,11 @@ jobs:
 
       - name: Get all added or modified files
         run: |
-          BASE_BRANCH=${{ github.base_ref }} || "dev"
+          BASE_BRANCH=${{ github.base_ref }} || "dummy-dev"
           git fetch origin $BASE_BRANCH
           if ! git rev-parse --verify --quiet origin/$BASE_BRANCH; then
-            echo "Fallback to dev branch because $BASE_BRANCH does not exist."
-            BASE_BRANCH="dev"
+            echo "Fallback to dummy-dev branch because $BASE_BRANCH does not exist."
+            BASE_BRANCH="dummy-dev"
             git fetch origin $BASE_BRANCH
           fi
           ALL_CHANGED_FILES=$(git diff --name-only origin/$BASE_BRANCH HEAD)
@@ -87,7 +87,7 @@ jobs:
           fi
 
       - name: Format code with Black and commit changes
-        if: ${{ env.FILES != '' && github.ref != 'refs/heads/dev' }}
+        if: ${{ env.FILES != '' && github.ref != 'refs/heads/dummy-dev' }}
         env:
           BRANCH_NAME: ${{ github.head_ref || github.ref }}
         run: |
@@ -161,27 +161,27 @@ jobs:
         id: set_current_branch_error_count
         run: echo "error_count=$(cat mypy_current_branch_error_count.txt)" >> $GITHUB_OUTPUT
 
-      - name: Run mypy on the dev branch
-        if: github.ref != 'refs/heads/dev'
+      - name: Run mypy on the dummy-dev branch
+        if: github.ref != 'refs/heads/dummy-dev'
         run: |
-          git checkout dev
-          python -m mypy . 2>&1 | tee mypy_dev_branch_report.txt || true
-          grep -c "error:" mypy_dev_branch_report.txt > mypy_dev_branch_error_count.txt
+          git checkout dummy-dev
+          python -m mypy . 2>&1 | tee mypy_dummy-dev_branch_report.txt || true
+          grep -c "error:" mypy_dummy-dev_branch_report.txt > mypy_dummy-dev_branch_error_count.txt
 
-      - name: Set dev branch error count as output
-        id: set_dev_branch_error_count
-        if: github.ref != 'refs/heads/dev'
-        run: echo "error_count=$(cat mypy_dev_branch_error_count.txt)" >> $GITHUB_OUTPUT
+      - name: Set dummy-dev branch error count as output
+        id: set_dummy-dev_branch_error_count
+        if: github.ref != 'refs/heads/dummy-dev'
+        run: echo "error_count=$(cat mypy_dummy-dev_branch_error_count.txt)" >> $GITHUB_OUTPUT
 
       - name: Compare mypy reports
-        if: github.ref != 'refs/heads/dev'
+        if: github.ref != 'refs/heads/dummy-dev'
         run: |
           CURRENT_ERRORS=${{ steps.set_current_branch_error_count.outputs.error_count }}
-          dev_ERRORS=${{ steps.set_dev_branch_error_count.outputs.error_count }}
+          dummy-dev_ERRORS=${{ steps.set_dummy-dev_branch_error_count.outputs.error_count }}
           echo "Current branch mypy errors: $CURRENT_ERRORS"
-          echo "dev branch mypy errors: $dev_ERRORS"
-          if [ $CURRENT_ERRORS -gt $dev_ERRORS ]; then
-            echo "Mypy error count has increased from the dev branch to the current branch ($dev_ERRORS -> $CURRENT_ERRORS)."
+          echo "dummy-dev branch mypy errors: $dev_ERRORS"
+          if [ $CURRENT_ERRORS -gt $dummy-dev_ERRORS ]; then
+            echo "Mypy error count has increased from the dummy-dev branch to the current branch ($dummy-dev_ERRORS -> $CURRENT_ERRORS)."
             exit 1
           else
             echo "No increase in mypy errors found."
@@ -189,7 +189,7 @@ jobs:
         continue-on-error: true
 
       - name: Checkout current branch
-        if: github.ref != 'refs/heads/dev'
+        if: github.ref != 'refs/heads/dummy-dev'
         run: git checkout ${{ github.head_ref }}
 
       - name: Set color and status for Flake8 badge
@@ -251,13 +251,13 @@ jobs:
           URL: ${{ github.event.pull_request.comments_url }}
         run: |
           MY_ERROR_COUNT=${{ steps.set_current_branch_error_count.outputs.error_count }}
-          dev_ERRORS=${{ steps.set_dev_branch_error_count.outputs.error_count }}
+          dummy-dev_ERRORS=${{ steps.set_dummy-dev_branch_error_count.outputs.error_count }}
           if [ -n "$URL" ]; then
             PYTEST_COVERAGE="Current Coverage: ${{ steps.coverage.outputs.coverage_percentage }}%"
             echo "$PYTEST_COVERAGE"
             MYPY_ERRORS="Mypy errors on ${{ github.head_ref }} branch: $MY_ERROR_COUNT"
-            MYPY_ERRORS="$MYPY_ERRORS\nMypy errors on dev branch: $dev_ERRORS"
-            DIFF=$((MY_ERROR_COUNT - dev_ERRORS))
+            MYPY_ERRORS="$MYPY_ERRORS\nMypy errors on dummy-dev branch: $dummy-dev_ERRORS"
+            DIFF=$((MY_ERROR_COUNT - dummy-dev_ERRORS))
             if [ $DIFF -gt 0 ]; then
               MYPY_ERRORS="$MYPY_ERRORS\n$DIFF more errors on ${{ github.head_ref }} branch"
             elif [ $DIFF -lt 0 ]; then
